name: Build and Release

on:
  push:
    branches: [main]
    tags: ["R*"]
  pull_request:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-windows-release:
    name: Windows x64 Release
    if: startsWith(github.ref, 'refs/tags/')
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Windows x64
            os: windows-latest
            libc: ""
            artifact_name: llvmexpr-windows-x64-static-llvm21-static-shaderc
            library_name: libllvmexpr.dll
    uses: ./.github/workflows/reusable-windows-release.yml
    with:
      os: ${{ matrix.os }}
      libc: ${{ matrix.libc }}
      artifact_name: ${{ matrix.artifact_name }}
      library_name: ${{ matrix.library_name }}

  build-all:
    name: ${{ matrix.name }}
    if: ${{ !startsWith(github.ref, 'refs/tags/') }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Linux x64-glibc
            os: ubuntu-latest
            libc: glibc
            artifact_name: llvmexpr-linux-x64-glibc-static-llvm21-static-shaderc
            library_name: libllvmexpr.so

          - name: macOS arm64
            os: macos-latest
            libc: ""
            artifact_name: llvmexpr-macos-arm64-static-llvm20-static-shaderc
            library_name: libllvmexpr.dylib
          - name: Windows x64
            os: windows-latest
            libc: ""
            artifact_name: llvmexpr-windows-x64-static-llvm21-static-shaderc
            library_name: libllvmexpr.dll
    uses: ./.github/workflows/reusable-build-all.yml
    with:
      os: ${{ matrix.os }}
      libc: ${{ matrix.libc }}
      artifact_name: ${{ matrix.artifact_name }}
      library_name: ${{ matrix.library_name }}

  release:
    name: Release
    needs: build-windows-release
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write
    uses: ./.github/workflows/reusable-release.yml
